### PR TITLE
TSE Review TicTacToe Milestone 2: User Interface

### PR DESCRIPTION
**Pull request by aecordova**
Milestone 2:

1 - Added the title of the game
2 - Added prompts for usernames and choice of X's or O's
3 - Added the look of the game display

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work @team :clap: However, some requirements need to be implemented in order for us to approve the milestone. check  :arrow_down: 

- **[REQUIRED]** Please enable you stickler so it shows if your code passes the linter checks

##### Behaviour

* [ ] In this step, not everything must work, the point is to make sure that students thought about everything listed below. They might do it only with inline comments. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
  * [ ] `[REQUIRED]` game tells which player turn it is
  * [ ] `[REQUIRED]` game asks player to select from available moves
  * [ ] `[REQUIRED]` game informs player if selected move is invalid
  * [ ] `[REQUIRED]` game displays board after player move
  * [ ] `[REQUIRED]` game informs player if selected move is a winning move
  * [ ] `[REQUIRED]` game informs player if selected move is a draw move
  * [ ] `[REQUIRED]` game repeats all actions for next player's move

##### Implementation details

* [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [ ] Inside the game loop, all instructions should be repeated for each player **individually**
* [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with a boolean variable as below:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by simoxsimo** [comment]
Pull Request closed to fix stickler issues

**Comment by simoxsimo** [comment]
Fixed Stickler problem

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Nice progress :+1: 
Your game looks fine. You handled the interface and player logic fine. However, you still haven't shown us how you will handle the game logic. 
How will you handle the win or draw situations?
As pointed by the previous TSE,
- [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
- [ ] Inside loop, student should all actions repeated for each move
- [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
````
#### Make those changes and resubmit for another review.

### Martin Afani

**Comment by simoxsimo** [comment]
@whiz25 Thank you for your review the reason behind not showing how we handled the win/draw conditions is because we are still in the user interface milestone we didn't advance yet to the next milestone for the game logic.

**Comment by whiz25** [comment]
@simoxsimo 
I am not saying the game logic should work. In this milestone, you are supposed to lay the foundation upon which you will build in the next milestone.
The loop for the game is required. Please add it but it should not work. Just show us you have thought about it.

**Review by suretrust — APPROVED** [review]
Hi team, 👋 

### Great job implementing the suggestions. 🙌 Let's get this merged! 👍 

_Good luck on other milestones and happy coding!_ 🎉

**Pull request merged**
